- name: "Update apt packages"
  become: true
  apt:
    update_cache: yes

- name: "Upgrade apt packages"
  become: true
  apt:
    upgrade: yes

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "Install npm and tar"
  become: true
  apt:
    name: ["npm", "tar"]
    state: "latest"
    update_cache: yes

- name: "install n"
  become: yes
  npm:
    name: n
    global: yes
    production: yes

- name: "install nodejs 13.8.0"
  become: yes
  shell: n 13.8.0

- name: "Install pm2"
  become: true
  npm:
    name: "pm2"
    global: yes
    production: yes
    state: "present"