- name: "Creates directory"
  become: yes
  file:
    path: "~/backend-server"
    state: "directory"
    mode: 0755

- name: "Copy compressed file to backend-server folder"
  become: yes
  copy:
    src: "artifact.tar.gz"
    dest: "~/backend-server/artifact.tar.gz"

- name: "Extract backend"
  become: yes
  unarchive:
    remote_src: yes
    src: "~/backend-server/artifact.tar.gz"
    dest: "~/backend-server"

- name: "Run the web server"
  become: yes
  shell:
    cmd: |
      cd ~/backend-server
      npm install
      pm2 stop default
      pm2 start npm -- start --wait-ready
      # cd dist
      # pm2 start main.js --update-env